projects:
  emberamplify:
    schemaPath: app/graphql/schema.json
    includes:
      - app/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: app/graphql
